config/routes.rb
Rails.application.routes.draw do

  get 'database/index'

  get 'payments/show' 

  get 'industry_links/show'

  get 'certified_contractors/show'

  get 'about/show'

  get 'products/supertherm'

  get 'products/rustgrip'

  get 'products/hotpipe'

  root 'home#main'
  get 'home/main'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/certified_contractors_controller.rb
class CertifiedContractorsController < ApplicationController
  def show
  end
end

app/controllers/database_controller.rb
class DatabaseController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
end

app/controllers/industry_links_controller.rb
class IndustryLinksController < ApplicationController
  def show
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def supertherm
  end

  def rustgrip
  end

  def hotpipe
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certified_contractors_helper.rb
module CertifiedContractorsHelper
end

app/helpers/database_helper.rb
module DatabaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/industry_links_helper.rb
module IndustryLinksHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about/show.html.erb
<%= render 'home/nav2' %>

<div class="about-background"><img src="/assets/about.png" alt="" height="550px" width="550px"/>
</div>
<div class="about-container">

  About Us

  <div class="about-us">
    <p>
<br><br>
Eagle Specialized Coatings And Protected Environments ( E.S.C.A.P.E. ) a division of DW Pearce Enterprises Ltd is the Canadian and Pacific West Coast authorized distributor
for Superior Products International II, Inc. a US manufacturer of leading edge, high tech industrial protective coatings with a world wide distributor network.
<br><br>

 There is only one thought you need to keep in mind...if you don't see the solution for your problem here, it probably hasn't been created...at least not yet!
    </p>

  </div>

</div>


<%= render 'home/footer' %>

app/views/certified_contractors/show.html.erb
<%= render 'home/nav2' %>


<div class="certified-contractors-background">
  <img src="/assets/certcontr.png" alt="" height="550px" width="550px"/>
</div>

<div class="certified-contractors-container">

Certified Contractors

  <div class="certified-contractors">
    <p>

Eagle's philosophy is that the best projects result from the integration and teamwork between owner, designer, construction manager \ general contractor, trade contractors and suppliers, all of whom become aligned with the key project objectives.
<br><br>
Early input from our Certified Contractors and Superior Products International, combined with our own coatings expertise enables optimization of the recommended coating system, while achieving critical schedule, quality, cost and functionality objectives. We look to build long term relationships with the owner, designer, general contractor, Certified Contractors \ Superior team members.
<br><br>
Our team is experienced, creative and motivated and is well supported by industry leading coating systems.
    </p>

  </div>

</div>


<%= render 'home/footer' %>

app/views/database/index.html.erb
<%= render 'home/nav2' %>


<div class="database-background">
<img src="/assets/product_database_grey.png" alt="" height="550px" width="450px" />

</div>

  <div class="database-container">
    Product Database
  </div>
    <div class="thermal-database">
      <div class="supertherm-db" >
        <a href="/products/supertherm" >SuperTHERM<sup>®</sup><span class="description">Multi Layer Ceramic Insulation Coating
      </span>
<br>
      <i>Engineered to Repel Radiated Heat.</i>
    </a>
  </div>
<br><br><br>
      <a href="/products/sunshield" >SunSHIELD<sup>®</sup><span class="description">Multi Layer Ceramic Insulation Coating</span>
<br>
      <i>Engineered to Repel Radiated Heat.</i>
      </a>
<br><br><br>
      <a href="" >EpoxoTHERM<sup>®</sup><span class="description">
        Multi-Layer Ceramic Insulation Coating
      </span>
<br>
        <i>Engineered to Repel Radiated Heat.</i>
      </a>
<br><br><br>
      <a href="" >Hot-Surface COATING<sup>®</sup><span class="description">
       Multi-Layer Ceramic Insulation Coating
     </span>
<br>
        <i>Engineered to Block Conducted Heat.</i><span class="mid-temp">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspMid Temp (200°F \ 93.33°C to 350°F \ 177°C) </span>
      </a>
<br><br><br>
    <a href="" >Hot-Pipe COATING<sup>®</sup></a>
  </div>
  <div class="corrosion-database">
<a href="" >RustGRIP<sup>®</sup></a>
<br>
    <a href="" >RustGRIP 1000<sup>®</sup></a>
<br>
    <a href="" >RustGRIP-E</a><sup>®</sup></a>
<br>
    <a href="" >Moist Metal GRIP<sup>®</sup></a>
<br>
    <a href="" >Lining-Kote UHS<sup>®</sup></a>
  </div>
  <div class="fire-database">
      <a href="" >Omega FIRE<sup>®</sup></a>
  <br>
      <a href="" >Penetrating Chemical</a>
  <br>
      <a href="" >Interior Latex</a>
  <br>
      <a href="" >Polyurethane</a>
  <br>
      <a href="" >SafeCOAT PVC</a>
    </div>
    <div class="concrete-database">
      <a href="" >SP InterLOCK / InnerSEAL<sup>®</sup></a>
      <br>
      <a href="" >SuperBASE(HS)<sup>®</sup></a>
      <br>
      <a href="" >TotalSEAL</a><sup>®</sup> <i>(U.S. only)</i></a>
      <br>
      <a href="" >TotalSEAL(HS)<sup>®</sup></a>
      <br>
      <a href="" >Liquid Membrane<sup>®</sup></a>
    </div>
    <div class="graffiti2-database">
      <a href="" >EnamoGRIP(Coloured)<sup>®</sup></a>
      <br>
      <a href="" >EnamoGRIP(Clear) <sup>®</sup><i>(U.S. only)</i></a>
      <br>
      <a href="" >EnamoGRIP(Clear) 1000<sup>®</sup></a>
      <br>
      <a href="" >EnamoGRIP(Clear) 3700 <sup>®</sup><i>(U.S. only)</i></a>
      <br>
      <a href="" >EnamoGRIP(Clear) 5000<sup>®</sup></a>
      <br>
      <a href="" >AquaPOX<sup>®</sup></a>
      <br>
      <a href="" >Graffiti CLEANER<sup>®</sup></a>
    </div>


  <!-- <div class="phone">
    <%= link_to image_tag "phonenew.png", height: "90px", width: "90px" %>
  </div>


    <div class="phone-number"><img src="/assets/phonenumber.png" class="phone-full" height="45px" /></div>


  <a href="http://www.spicoatings.com/" class="auth"> -->


  <%= render 'home/footer' %>

app/views/home/_footer.html.erb
<div class="footer-container">

    <div class="phone">
      <a href="#" >
        <img src="/assets/phonenew.png" alt="" height="90px" width="90px" />
      </a>
    </div>

    <div class="phone-number">
      <a href="#">
        <img src="/assets/phonenumber.png" class="phone-full" height="45px" />
      </a>
    </div>

    <div class="spi">
      <a href="http://www.spicoatings.com/" class="auth">
        <img src="/assets/spi-authorized.png" alt="" class="spi-authorized" />
        <p class="spi-authorized-title">
        All products<br>
        manufactured by
        <br>
        Superior Products<br>
        International II, Inc.
        </p>
      </a>
    </div>

    <a href="/database/index" class="chat">
      <%= image_tag "chat.png", height: "44px", width: "44px" %>
    </a>

    <div id="about-wrapper"><a href="/about/show" class="about hvr-float-shadow">
      <%= image_tag "about.png", height: "52px", width: "50px" %>
    </a><p class="about-us-title">About Us</p></div>

    <div id="contact-wrapper"><a href="mailto:president@eaglecoatings.net" class="contact hvr-float-shadow">
      <%= image_tag "email.png", height: "55px", width: "55px" %>
    </a><p class="contact-us-title"> Contact </p></div>

    <div id="twitter-wrapper"><a href="https://twitter.com/?lang=en" class="tw hvr-float-shadow">
        <%= image_tag "tw.png", height: "53px", width: "53px" %>
    </a><p class="twitter-title">Twitter</p></div>

    <div id="facebook-wrapper"><a href="https://www.facebook.com/" class="facebook hvr-float-shadow">
      <%= image_tag "facebook.png", height: "52px", width: "52px" %>
    </a><p class="facebook-title">Facebook</p></div>

    <div id="youtube-wrapper"><a href="https://www.youtube.com/channel/UCERGEwuO7jKen536Drjfirw" class="youtube hvr-float-shadow">
      <%= image_tag "youtube.png", height: "53px", width: "53px" %>
    </a><p class="youtube-title">YouTube</p></div>

    <div id="industry-links-wrapper"><a href="/industry_links/show"class="links hvr-float-shadow">
      <%= image_tag "links.png", height: "53px", width: "52px" %>
    </a><p class="industry-links-title">Industry</p></div>

    <div id="certified-contractors-wrapper"><a href="/certified_contractors/show"class="contractors hvr-float-shadow">
      <%= image_tag "certcontr.png", height: "55px", width: "55px" %>
    </a><p class="certified-contractors-title">Contractors</p></div>

    <div id="pay-wrapper"><a href="/payments/show" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>
      </a><p class="pay-title">Pay</p></div>

  </div>

app/views/home/_footer2.html.erb
    <a href="/database/index" class="chat">
      <%= image_tag "chat.png", height: "44px", width: "44px" %>
    </a>



    <!-- <a href="/about/show" class="about hvr-float-shadow">
      <%= image_tag "about.png", height: "50px", width: "50px" %>
    </a>

    <a href="mailto:president@eaglecoatings.net" class="email hvr-float-shadow">
      <%= image_tag "email.png", height: "55px", width: "55px" %>
    </a>

    <a href="https://www.facebook.com/" class="facebook hvr-float-shadow">
      <%= image_tag "facebook.png", height: "52px", width: "52px" %>
    </a>

    <a href="https://twitter.com/?lang=en" class="tw hvr-float-shadow">
      <%= image_tag "tw.png", height: "54px", width: "54px" %>
    </a>

    <a href="https://www.youtube.com/channel/UCERGEwuO7jKen536Drjfirw" class="youtube hvr-float-shadow">
      <%= image_tag "youtube.png", height: "53px", width: "53px" %>
    </a>

    <a href="/industry_links/show"class="links hvr-float-shadow">
      <%= image_tag "links.png", height: "52px", width: "52px" %>
    </a>

    <a href="/certified_contractors/show"class="contractors hvr-float-shadow">
      <%= image_tag "certcontr.png", height: "55px", width: "55px" %>
    </a> -->



      <a href="/payments/show" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>
      </a>

app/views/home/_nav.html.erb
  <!-- Header -->

  <div class="container">

    <div class="logo"> <a href="/" class="logo-text-link">
      <h1 class="logo-text">
      Eagle Specialized Coatings
      <br><br>
      &
      <br><br>
      Protected Environments
      </a>
      <div class="logo-img">
        <%= link_to image_tag("eagle_vanacal.png", height: "340px", width: "440px"), root_path %>
      </div>
      <div class="logo-img2">
        <%= link_to image_tag("eagle_vanacalbl.png", height: "340px", width: "440px"), root_path %>
      </div>
      </h1>
    </div>

    <a href="/products/supertherm" class="supertherm hvr-underline-from-center">
      SuperTHERM<sup>®</sup>
    </a>

    <a href="/products/rustgrip" class="rustgrip hvr-underline-from-center">
      RustGRIP<sup>®</sup>
    </a>

    <a href="/products/hotpipe" class="hot-pipe hvr-underline-from-center">
      Hot-Pipe COATING<sup>®</sup>
    </a>

  </div>




  <a href="/database/index" class="databaselayer">
    <img src="/assets/product_database_grey.png" height="38px" width="36px" alt="" />
  </a>
  <a href="/database/index" class="product-database-title">
      <%= image_tag "productdatabase.png", size: "145x20" %>
  </a>

  <!-- <div class="database-layer">
    <%= image_tag "layer1b.png", size: "55x55" %>
  </div>
  <div class="database-layer2">
    <%= image_tag "layer2.png", size: "55x55" %>
  </div>
  <div class="database-layer3">
    <%= image_tag "layer3.png", size: "55x55" %>
  </div>
  </div>
 -->

<!-- <img class="xyz" data-alt-src="/assets/product_database_grey.png" src="/assets/layer2.png" height="46px" width="38px"/>
<script type="text/javascript">
var sourceSwap = function () {
  var $this = $(this);
  var newSource = $this.data('alt-src');
  $this.data('alt-src', $this.attr('src'));
  $this.attr('src', newSource);
}
$(function () {
  $('img.xyz').hover(sourceSwap, sourceSwap);
});
</script> -->

<!-- <script type="text/javascript">

$( ".databaselayer" ).mouseenter(function() {
  $( ".database-layer3" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer2" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $(this).hide()
});
$( ".databaselayer" ).mouseleave(function() {
  $( ".database-layer3" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer2" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $(this).show()
});
</script> -->

  <!-- <script type="text/javascript">
  $(".databaselayer").mouseenter(function() {

      $(".databaselayer").fadeOut({
      }, {
        duration: 500,
      });

      $('.database-layer').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer2').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer3').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer').animate({ up: "+=10px" }, 'slow');
      $('.database-layer2').animate({ left: "-=10px" }, 'slow');
      $('.database-layer3').animate({ up: "-=10px" }, 'slow');
      $(".database-layer2").fadeIn({
      }, {
        duration: 500,
      });
      $(".database-layer3").fadeIn({
      }, {
        duration: 500,
      });
  });
  $(".databaselayer").mouseleave(function() {

      // $(this).fadeIn({
      // }, {
      //   duration: 500,
      // });
      $(".database-layer").fadeOut({
      }, {
        duration: 500,
      });
      $(".database-layer2").fadeOut({
      }, {
        duration: 500,
      });
      $(".database-layer3").fadeOut({
      }, {
        duration: 500,
      });
      $(".databaselayer").fadeIn({
      }, {
        duration: 500,
      });
  });
  </script> -->

  <div class="magnifying-glass">
    <%= link_to image_tag "mg.png", height: "40px", width: "40px" %>
  </div>

    <div class="search-box">
    </div>

<hr>



  <!-- Footer -->




    <a href="#" class="chat">
      <%= image_tag "chat.png", height: "44px", width: "44px" %>
    </a>



    <a href="/about/show" class="about hvr-float-shadow">
      <%= image_tag "about.png", height: "50px", width: "50px" %>
    </a>

    <a href="mailto:president@eaglecoatings.net" class="email hvr-float-shadow">
      <%= image_tag "email.png", height: "55px", width: "55px" %>
    </a>

    <a href="https://www.facebook.com/" class="facebook hvr-float-shadow">
      <%= image_tag "facebook.png", height: "52px", width: "52px" %>
    </a>

    <a href="https://twitter.com/?lang=en" class="tw hvr-float-shadow">
      <%= image_tag "tw.png", height: "54px", width: "54px" %>
    </a>

    <a href="https://www.youtube.com/channel/UCERGEwuO7jKen536Drjfirw" class="youtube hvr-float-shadow">
      <%= image_tag "youtube.png", height: "53px", width: "53px" %>
    </a>

    <a href="/industry_links/show" class="links hvr-float-shadow">
      <%= image_tag "links.png", height: "52px", width: "52px" %>
    </a>

    <a href="/certified_contractors/show" class="contractors hvr-float-shadow">
      <%= image_tag "certcontr.png", height: "55px", width: "55px" %>
    </a>



      <a href="/payments/show" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>

      </a>



<!-- Title -->

    <!-- <div id="wrapper">

      <a href="/payment" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>
        <p class="title">
          Payments
        </p>
      </a>

    </div> -->
  </div>

app/views/home/_nav2.html.erb
<!-- <header>
  <img src="eagle_vanacal.png" alt="" />
  <img src="eagle_vanacalbl.png" alt="" />

  <nav>
    <ul>
      <li><a href="#">SuperTHERM<sup>®</sup></a></li>
      <li><a href="#">RustGRIP<sup>®</sup></a></li>
      <li><a href="#">Hot-Pipe COATING<sup>®</sup></a></li>
    </ul>
  </nav>
</header> -->














<!-- <div class="nav-container"> -->
  <div class="logo">

    <div class="logo-text-container">
      <a href="/" class="logo-text-link">
        <h1 class="logo-text">
          Eagle Specialized Coatings
          <br><br>
          &
          <br><br>
          Protected Environments
        </h1>
       </a>
    </div>

    <div class="logo-img-container">
      <div class="logo-img">
        <%= link_to image_tag("eagle_vanacal.png", height: "240px", width: "340px"), root_path %>
      </div>
      <div class="logo-img2">
        <%= link_to image_tag("eagle_vanacalbl.png", height: "240px", width: "340px"), root_path %>
      </div>
    </div>
  </div>

  <div class="nav-products">
    <a href="/products/supertherm" class="supertherm hvr-underline-from-center">
      SuperTHERM<sup>®</sup>
    </a>
    <a href="/products/rustgrip" class="rustgrip hvr-underline-from-center">
      RustGRIP<sup>®</sup>
    </a>
    <a href="/products/hotpipe" class="hot-pipe hvr-underline-from-center">
      Hot-Pipe COATING<sup>®</sup>
    </a>
  </div>

  <!-- <div class="search-container"> -->

  <!-- <div class="magnifying-glass">
</div> -->

    <!-- <div class="search-box">
    </div> -->
    <div class="magnifying-glass">
      <%= link_to image_tag "mg.png", height: "40px", width: "40px" %>
    </div>

    <div class="databaselayer">
      <%= link_to image_tag "product_database_grey.png", height: "40px", width: "40px" %>
    </div>
<!-- <br><br><br> -->
    <hr>
      <!-- <a href="/database/index" class="databaselayer">
      <img src="/assets/product_database_grey.png" height="38px" width="36px" alt="" />
    </a> -->

    <!-- <a href="/database/index" class="product-database-title">
      <%= image_tag "productdatabase.png", size: "145x20" %>
    </a> -->
  <!-- </div> -->


<!-- </div> -->

app/views/layouts/_nav.html.erb
  <!-- Header -->

  <div class="container"><div class="logo"> <a href="/" class="logo-text-link"><h1 class="logo-text">
      Eagle Specialized Coatings
      <br><br>
      &
      <br><br>
      Protected Environments
      </a>
      <div class="logo-img">
        <%= link_to image_tag("eagle_vanacal.png", height: "340px", width: "440px"), root_path %>
      </div>
      <div class="logo-img2">
        <%= link_to image_tag("eagle_vanacalbl.png", height: "340px", width: "440px"), root_path %>
      </div>
    </h1>
  </div>

  <div class="supertherm hvr-underline-from-center">
    <%= link_to "SuperTHERM®", products_supertherm_path %>
  </div>

  <a href="/products/rustgrip" class="rustgrip hvr-underline-from-center">
    RustGRIP®
  </a>

  <div class="hot-pipe hvr-underline-from-center">
    <%= link_to "Hot-Pipe COATING®", products_hotpipe_path %>
  </div>




  <div class="database-layer">
    <%= image_tag "layer1b.png", size: "55x55" %>
  </div>
  <div class="database-layer2">
    <%= image_tag "layer2.png", size: "55x55" %>
  </div>
  <div class="database-layer3">
    <%= image_tag "layer3.png", size: "55x55" %>
  </div>
</div>
  <div class="databaselayer-container"><div class="databaselayer">
    <%= image_tag "product_database_grey.png", size: "38x46" %>
</div>

<!-- <img class="xyz" data-alt-src="/assets/product_database_grey.png" src="/assets/layer2.png" height="46px" width="38px"/>
<script type="text/javascript">
var sourceSwap = function () {
  var $this = $(this);
  var newSource = $this.data('alt-src');
  $this.data('alt-src', $this.attr('src'));
  $this.attr('src', newSource);
}
$(function () {
  $('img.xyz').hover(sourceSwap, sourceSwap);
});
</script> -->

<script type="text/javascript">

$( ".databaselayer" ).mouseenter(function() {
  $( ".database-layer3" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer2" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $(this).hide()
});
$( ".databaselayer" ).mouseleave(function() {
  $( ".database-layer3" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer2" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $( ".database-layer" ).animate({
    opacity: "toggle"
  }, 5000, "linear")
  $(this).show()
});
</script>

  <!-- <script type="text/javascript">
  $(".databaselayer").mouseenter(function() {

      $(".databaselayer").fadeOut({
      }, {
        duration: 500,
      });

      $('.database-layer').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer2').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer3').fadeIn({queue: false, duration: 'slow'});
      $('.database-layer').animate({ up: "+=10px" }, 'slow');
      $('.database-layer2').animate({ left: "-=10px" }, 'slow');
      $('.database-layer3').animate({ up: "-=10px" }, 'slow');
      $(".database-layer2").fadeIn({
      }, {
        duration: 500,
      });
      $(".database-layer3").fadeIn({
      }, {
        duration: 500,
      });
  });
  $(".databaselayer").mouseleave(function() {

      // $(this).fadeIn({
      // }, {
      //   duration: 500,
      // });
      $(".database-layer").fadeOut({
      }, {
        duration: 500,
      });
      $(".database-layer2").fadeOut({
      }, {
        duration: 500,
      });
      $(".database-layer3").fadeOut({
      }, {
        duration: 500,
      });
      $(".databaselayer").fadeIn({
      }, {
        duration: 500,
      });
  });
  </script> -->

  <div class="magnifying-glass">
    <%= link_to image_tag "mg.png", height: "40px", width: "40px" %>
  </div>
    <script>
      // $(".magnifying-glass").hover(function(){
      //   $(this).animate({
      //     left: "1600px",
      //     height: "+=180px",
      //     width: "=+180px",
      //   }, {
      //     duration: 500,
      //   });
      // });
      // $(".magnifying-glass").hover(function(){
      //   $(this).animate({
      //     left: "1800px",
      //   }, {
      //     duration: 500,
      //   });
      // });
      $( ".magnifying-glass" ).mouseenter(function() {
  $( ".search-box" ).fadeIn( "slow", function() {
    $(this).animate()
    // Animation complete
  });
});
      $( ".magnifying-glass" ).mouseleave(function() {
  $( ".search-box" ).fadeOut( "slow", function() {
    // Animation complete
  });
});


    </script>
    <div class="search-box">
    </div>

<hr>



  <!-- Footer -->


  <div class="phone">
    <%= link_to image_tag "phonenew.png", height: "90px", width: "90px" %>
  </div>
    <script>
      $.fn.animateRotate = function(angle,prevAngle, duration, easing, complete) {
          var args = $.speed(duration, easing, complete);
          var step = args.step;
          return this.each(function(i, e) {
              args.complete = $.proxy(args.complete, e);
              args.step = function(now) {
                  $.style(e, 'transform', 'rotate(' + now + 'deg)');
                  if (step) return step.apply(e, arguments);
              };

              $({deg: prevAngle}).animate({deg: angle}, args);
          });
      };
      var angle = 0;
      var prevAngle = 0;


      $(".phone").mouseenter(function(e) {
          prevAngle = angle
          angle -= 100;
          $(this).animateRotate(angle, prevAngle, 500);
          e.preventDefault();
          $(this).animate({
            left: "800px",
            opacity: 1
          }, {
            duration: 500,
            queue: false
          });
      });
      $(".phone").mouseleave(function(e) {
        prevAngle = angle
        angle += 100;
        $(this).animateRotate(angle, prevAngle, 500);
        e.preventDefault();
        $(this).animate({
          left: "905px",
          opacity: 1
          }, {
            duration: 500,
            queue: false
          });
        });

    </script>

<div class="wrapper">

</div>
    <a href="#" class="chat">
      <%= image_tag "chat.png", height: "44px", width: "44px" %>
    </a>

  <!-- $( document ).click(function() { -->
  <script>
  $( ".phone" ).mouseenter(function() {
  $( ".phone-number" ).toggle( "slide");
});
  $( ".phone" ).mouseleave(function() {
  $( ".phone-number" ).toggle( "slide");
});
</script>

<div class="phone-number"><img src="/assets/phonenumber.png" class="phone-full" height="45px" /></div>

<!-- <script>
$( document ).click(function() {
$( ".phone-number" ).show( "slide" );
});
</script> -->

    <a href="/about" class="about hvr-float-shadow">
      <%= image_tag "about.png", height: "50px", width: "50px" %>
    </a>

    <a href="/email" class="email hvr-float-shadow">
      <%= image_tag "email.png", height: "55px", width: "55px" %>
    </a>

    <a href="https://www.facebook.com/" class="facebook hvr-float-shadow">
      <%= image_tag "facebook.png", height: "52px", width: "52px" %>
    </a>

    <a href="https://twitter.com/?lang=en" class="tw hvr-float-shadow">
      <%= image_tag "tw.png", height: "54px", width: "54px" %>
    </a>

    <a href="https://www.youtube.com/channel/UCERGEwuO7jKen536Drjfirw" class="youtube hvr-float-shadow">
      <%= image_tag "youtube.png", height: "53px", width: "53px" %>
    </a>

    <a href="/industry_links"class="links hvr-float-shadow">
      <%= image_tag "links.png", height: "52px", width: "52px" %>
    </a>

    <a href="/certified_contractors"class="contractors hvr-float-shadow">
      <%= image_tag "certcontr.png", height: "55px", width: "55px" %>
    </a>



      <a href="/payment" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>

      </a>



<!-- Title -->

    <!-- <div id="wrapper">

      <a href="/payment" class="pay hvr-float-shadow">
        <%= image_tag "pay.png", class: "hover", height: "53px", width: "53px" %>
        <p class="title">
          Payments
        </p>
      </a>

    </div> -->
  </div>